name: gold-notify
on:
  schedule:
    - cron: '*/30 1-5 * * 0-4'
  # schedule:
  #   - cron: "0 0 * * *" 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: install py package
        run: pip install -r requirements.txt
      - name: execute py script # run the run.py to get the latest data
        run: python gold.py
        env:
          TOKEN: ${{ secrets.TOKEN }} 
